# _config.yml of learning-analytics

title: Learning Analytics
description: Visual presentation of student learning behavior.
baseurl: /learning-analytics/
url: https://sacren.github.io/learning-analytics/
author: © 2017 Jεan Sacren

timezone: America/Denver
encoding: utf-8

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
