# _config.yml of learning-analytics

title: Learning Analytics
description: Visual presentation of student learning behavior.
baseurl: /learning-analytics
url: ''
author: © 2018 Jεan Sacren

timezone: America/Denver
encoding: utf-8

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
